### ISSUE TITLE
Automatically create temp directory

### ISSUE THREAD

**Issue by jenrik** [Duckle29/ansible-dhparams#2]
I suggest using the [tempfile](https://docs.ansible.com/ansible/latest/modules/tempfile_module.html) module to automatically create a temporary directory instead of having it as an argument. This would also solve a potential issue with colliding files when deploying to multiple servers.

**Comment by Duckle29** [comment]
This has been done in 545a548adb8c0dc23318f1fcf7509b0e8ecf49a3
